name: json data refresh

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run data refresh
        env:
          EXCEL_GITHUB_PAT: ${{ secrets.EXCEL_GITHUB_PAT }}
        run: python Data_refresh.py
