name: Update output.json

on:
  workflow_dispatch:

jobs:
  update-output-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests

      - name: Run Data_refresh.py script
        env:
          EXCEL_GITHUB_PAT: ${{ secrets.EXCEL_GITHUB_PAT }}
        run: python Data_refresh.py

      - name: Commit and push output.json if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add output.json

          if ! git diff --cached --quiet; then
            git commit -m "自动更新 output.json 文件"
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/BYTX-YGJ/salary-check-bot.git
            git push origin HEAD:main
          else
            echo "没有文件变动，无需提交"
          fi
