name: Salary Check Reminder

on:
  schedule:
    - cron: '0 1-11 8-14 * *'  # 每月10-18号，UTC 0:30-10:30（北京时间8:30-18:30）
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run salary check
        env:
          EXCEL_GITHUB_PAT: ${{ secrets.EXCEL_GITHUB_PAT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: "smtp.qiye.aliyun.com"
          SMTP_PORT: "465"
          REPLY_TO: ""
        run: python salary_check.py
