name: Salary Check Reminder

on:
  schedule:
    - cron: '0 1 8 * *'
    - cron: '0 2 8 * *'
    - cron: '0 3 8 * *'
    - cron: '0 4 8 * *'
    - cron: '0 5 8 * *'
    - cron: '0 6 8 * *'
    - cron: '0 7 8 * *'
    - cron: '0 8 8 * *'
    - cron: '0 9 8 * *'
    - cron: '0 10 8 * *'
    - cron: '0 11 8 * *'
    - cron: '0 1 9 * *'
    - cron: '0 2 9 * *'
    - cron: '0 3 9 * *'
    - cron: '0 4 9 * *'
    - cron: '0 5 9 * *'
    - cron: '0 6 9 * *'
    - cron: '0 7 9 * *'
    - cron: '0 8 9 * *'
    - cron: '0 9 9 * *'
    - cron: '0 10 9 * *'
    - cron: '0 11 9 * *'
    - cron: '0 1 10 * *'
    - cron: '0 2 10 * *'
    - cron: '0 3 10 * *'
    - cron: '0 4 10 * *'
    - cron: '0 5 10 * *'
    - cron: '0 6 10 * *'
    - cron: '0 7 10 * *'
    - cron: '0 8 10 * *'
    - cron: '0 9 10 * *'
    - cron: '0 10 10 * *'
    - cron: '0 11 10 * *'
    - cron: '0 1 11 * *'
    - cron: '0 2 11 * *'
    - cron: '0 3 11 * *'
    - cron: '0 4 11 * *'
    - cron: '0 5 11 * *'
    - cron: '0 6 11 * *'
    - cron: '0 7 11 * *'
    - cron: '0 8 11 * *'
    - cron: '0 9 11 * *'
    - cron: '0 10 11 * *'
    - cron: '0 11 11 * *'
    - cron: '0 1 12 * *'
    - cron: '0 2 12 * *'
    - cron: '0 3 12 * *'
    - cron: '0 4 12 * *'
    - cron: '0 5 12 * *'
    - cron: '0 6 12 * *'
    - cron: '0 7 12 * *'
    - cron: '0 8 12 * *'
    - cron: '0 9 12 * *'
    - cron: '0 10 12 * *'
    - cron: '0 11 12 * *'
    - cron: '0 1 13 * *'
    - cron: '0 2 13 * *'
    - cron: '0 3 13 * *'
    - cron: '0 4 13 * *'
    - cron: '0 5 13 * *'
    - cron: '0 6 13 * *'
    - cron: '0 7 13 * *'
    - cron: '0 8 13 * *'
    - cron: '0 9 13 * *'
    - cron: '0 10 13 * *'
    - cron: '0 11 13 * *'
    - cron: '0 1 14 * *'
    - cron: '0 2 14 * *'
    - cron: '0 3 14 * *'
    - cron: '0 4 14 * *'
    - cron: '0 5 14 * *'
    - cron: '0 6 14 * *'
    - cron: '0 7 14 * *'
    - cron: '0 8 14 * *'
    - cron: '0 9 14 * *'
    - cron: '0 10 14 * *'
    - cron: '0 11 14 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run salary check
        env:
          EXCEL_GITHUB_PAT: ${{ secrets.EXCEL_GITHUB_PAT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: "smtp.qiye.aliyun.com"
          SMTP_PORT: "465"
          REPLY_TO: ""
        run: python salary_check.py
