name: Salary Check Reminder

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run salary check
        env:
          EXCEL_GITHUB_PAT: ${{ secrets.EXCEL_GITHUB_PAT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_SERVER: "smtp.qiye.aliyun.com"
          SMTP_PORT: "465"
          REPLY_TO: ""
        run: python salary_check.py
      - name: Trigger data_refresh workflow
        run: |
         curl -X POST \
         -H "Accept: application/vnd.github+json" \
         -H "Authorization: token ${{ secrets.EXCEL_GITHUB_PAT }}" \
         https://api.github.com/repos/BYTX-YGJ/salary-check-bot/actions/workflows/data_refresh.yml/dispatches \
         -d '{"ref":"main"}'

